### PR TITLE
Update to Spring Data Neo4j 3.3.0.RELEASE and Neo4j 2.1.7

### PR DESCRIPTION
**Pull request by jexp**
Hi @sksamuel,
I'm not sure about your versioning scheme so I left it alone.

I would also like to know why you went with Spring Data Neo4j and not a more performant way of talking to Neo4j. (Raw HTTP or the JDBC driver).
Might be interesting to either change to either of that or to look into SDN4 or the JAVA-OGM that comes out soon.

Cheers

### CODE REVIEW

**Comment by gg4u** [comment]
Hi, migrated my db 2.1.5  to 2.1.7 but didn't work out.
migrated to 2.2.1 OK
but elasticsearch failed :
failed to create river [neo4j]
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [neo4j]
	at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:87)
	at org.elasticsearch.river.RiverModule.spawnModules(RiverModule.java:58)
	at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
	at org.elasticsearch.river.RiversService.createRiver(RiversService.java:137)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:275)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:269)
	at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:93)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: neo4j
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:73)
...9 more


I've tried to remove and reinstall the plugin.

Could you please tell me if river works fine with 2.2.1 ?
could you please address me on how to solve these issues?
much thank you

**Comment by gg4u** [comment]
Could you also check that river work with the last version of ElasticSearch ?
Now using 1.2.1.. 
it would be useful to have it sync with the last versions of both neo and ES..
thank you!

**Comment by gg4u** [comment]
Update - I tried to remove river and reinstall it, but no success - i found that even after:
bin/plugin -remove com.sksamuel.elasticsearch/elasticsearch-river-neo4j/1.2.1.1
I get message:
[Nocturne] failed to create river [neo4j][x_discovery]
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [neo4j]
so it looks like the plugin does not actually remove itself..

**Comment by sksamuel** [comment]
Rivers are deprecated now, so I'd start to look at alternatives

**Comment by sksamuel** [comment]
https://www.elastic.co/blog/deprecating_rivers

So this project won't be maintained anymore.

**Comment by gg4u** [comment]
oh nooo... which alternatives to index fulltext properties of neo ?
Could you please at least tell me how to actually remove it?
i mean, i removed it, no plugins installed, but when i run ES I still got:
[Nocturne] failed to create river [neo4j][x_discovery]
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [neo4j]

and I don't understand where does it come from..

**Comment by sksamuel** [comment]
I don't know either sorry. As for alternatives, I think the idea is you do
something outside of ES to push data in.

**Comment by ADSolutions** [comment]
Checkout: https://github.com/ADSolutions/NeoElasticIndexing
It sync nodes from Neo4j to Elasticsearch. 
Not very flexible nowadays but with more coding and time it can be a useful tool. 
With a worker we can loop it's execution.

**Comment by gg4u** [comment]
great @ADSolutions ! @jexp any plan to integrate Elastic search and neo? neo has lucene inside, but looks that the query are not very perfoming... it would be cool to dev own tool for integration between ES and neo, what do you think?

**Comment by jexp** [comment]
Good point, we're looking into ES integration from a users-guide standpoint anyway, just need an ES expert with capacity.

**Comment by sksamuel** [comment]
I am the author of https://github.com/sksamuel/elastic4s.
If I can help in anyway let me know.

**Pull request merged**
